name: Automaatika
favicon: null
layout_spectrum: 0.038988346233963966
typography_spectrum: 0.5271683286409825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8173239612951875
  lightness: 0.06781864096410573
  saturation: 0.32109757885336876
  rhythmicContrast: 0.3092447614762932
purpose: []
